### ISSUE TITLE
MissingPluginException(No implementation found for method ensureInitialized on channel window_manager_plus)

### ISSUE THREAD

**Issue by CaoGiaHieu-dev** [pichillilorenzo/window_manager_plus#1]
Hi . im just follow document and get this issue
```
════════ Exception caught by Flutter framework ═════════════════════════════════
The following MissingPluginException was thrown:
MissingPluginException(No implementation found for method ensureInitialized on channel window_manager_plus)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
platform_channel.dart:332
<asynchronous suspension>
#1      WindowManagerPlus.ensureInitialized (package:window_manager_plus/src/window_manager.dart:283:5)
window_manager.dart:283
<asynchronous suspension>
#2      _setDesktopWindow (package:super_up/main.dart:172:3)
main.dart:172
<asynchronous suspension>
#3      main.<anonymous closure> (package:super_up/main.dart:35:7)
main.dart:35
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
```

code example 
```
Future<void> _setDesktopWindow(List<String> args) async {
  // await the initialization of the plugin.
  // Here is an example of how to use ensureInitialized in the main function:
  await WindowManagerPlus.ensureInitialized(
      args.isEmpty ? 0 : int.tryParse(args[0]) ?? 0);

  // Now you can use the plugin, such as WindowManagerPlus.current
  WindowOptions windowOptions = WindowOptions(
    minimumSize: const Size(800, 600),
    size: const Size(1500, 1000),
    backgroundColor: Colors.transparent,
    skipTaskbar: true,
    title: SConstants.appName,
    titleBarStyle: VPlatforms.isWindows ? null : TitleBarStyle.hidden,
    fullScreen: false,
  );

  WindowManagerPlus.current.waitUntilReadyToShow(windowOptions, () async {
    await WindowManagerPlus.current.center();
    await WindowManagerPlus.current.show();
    await WindowManagerPlus.current.focus();
  });
}
```
```
void main(List<String> args) async {
  runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();

    if (VPlatforms.isDeskTop) {
      await _setDesktopWindow(args);
    }
....
```

**Comment by CaoGiaHieu-dev** [comment]
sorry . wrong setup on macos

**Comment by CaoGiaHieu-dev** [comment]
it happen on hot reload

**Comment by sennraf** [comment]
I get a MissingPluginException just on hot restart.
